---
site_name: "Kurs Netzwerk Grundlagen"
site_description: "Kurs Netzwerk Grundlagen"
site_url: ""
use_directory_urls: false
nav:
  - Einführung: "index.md"
  - Vorbereitungen: "vorbereitungen.md"
  - "Lab 0: Laborumgebung mit Containerlab": "lab0.md"
  - "Lab 1: Containerlab & Wireshark": "lab1.md"
  - "Lab 2: Ethernet Frameformate": "lab2.md"
  - "Lab 3: Hubs & Switches": "lab3.md"
  - "Lab 4: Ethernet, ARP & IP Adressen": "lab4.md"
  - "Lab 5: VLANs & statisches Routing": "lab5.md"
  - "Lab 6: Dynamisches Routing": "lab6.md"
  - "Lab 7: User Datagram Protocol (UDP)": "lab7.md"
  - "Lab 8: Dynamic Host Configuration Protocol (DHCP)": "lab8.md"
  - "Lab 9: Domain Name System Protokoll (DNS)": "lab9.md"
  - "Lab 10: Network Time Protocol (NTP)": "lab10.md"
  - "Lab 11: Transmission Control Protocol (TCP)": "lab11.md"

repo_url: https://github.com/tjbalzer/clab-lankurs
repo_name: clab-lankurs


theme:
  name: material
  logo: img/netzebw_logo.svg
  favicon: img/favicon.ico
  palette:
    # - scheme: slate
    #   primary: custom
    #   accent: custom

    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: cyan
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: yellow
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.tracking
    - content.code.copy
    - content.code.annotate
#extra_css:
#  - stylesheets/extra.css

plugins:
  - glightbox
    # - with-pdf:
    #     author: Martin Scheu, Mischa Diehm, Christopher Scherb
    #     copyright: ""
    #     cover_subtitle: Sichere und zuverlässige OT-Netzwerke designen
    #     output_path: ot-net101-workshop.pdf
        #enabled_if_env: ENABLE_PDF_EXPORT
        #
        # debug_html: true
        #show_anchors: true
        # verbose: true

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
